import { createClient } from '@clickhouse/client';

const clickhouse = createClient({
  host: process.env.CLICKHOUSE_HOST || 'http://localhost:8123',
  username: process.env.CLICKHOUSE_USER || 'default',
  password: process.env.CLICKHOUSE_PASSWORD || ''
});

export interface ReconciliationReport {
  clientId: string;
  periodStart: string;
  periodEnd: string;
  totalGrossSales: number;
  totalRefunds: number;
  totalDiscounts: number;
  trueNetRevenue: number;
  subscriptionRevenue: number;
  organicOneTimeRevenue: number;
  espAttributedGrossRevenue: number;
  espAttributedNetRevenue: number;
  reconciliationDiscrepancy: number; // Discrepancy between ESP claims and Shopify Net
  discrepancyPercentage: number;
  netContributionMargin: number; // True net revenue generated by retention channels
}

export class ReconciliationService {
  /**
   * Reconciles raw Shopify financial transactions with ESP attribution events
   * Deducts returns, discounts, taxes, and segments out recurring subscription rebills.
   */
  static async getReconciliation(
    tenantId: string,
    clientId: string,
    periodStart: string,
    periodEnd: string
  ): Promise<ReconciliationReport> {
    const query = `
      SELECT
        sum(gross_revenue) as total_gross,
        sum(refund_amount) as total_refunds,
        sum(net_revenue) as total_net,
        sumIf(net_revenue, is_subscription = 1) as sub_rev,
        sumIf(net_revenue, is_subscription = 0) as one_time_rev,
        sumIf(gross_revenue, channel IN ('email', 'sms')) as esp_gross,
        sumIf(net_revenue, channel IN ('email', 'sms') AND is_subscription = 0) as esp_true_net
      FROM events
      WHERE tenant_id = {tenantId:UUID}
        AND client_id = {clientId:UUID}
        AND event_type = 'placed_order'
        AND toDate(event_time) >= {periodStart:Date}
        AND toDate(event_time) <= {periodEnd:Date}
    `;

    const result = await clickhouse.query({
      query,
      query_params: { tenantId, clientId, periodStart, periodEnd },
      format: 'JSONEachRow'
    });

    const rows = await result.json<any>();
    const r = rows[0] || {};

    const totalGross = parseFloat(r.total_gross || '0');
    const totalRefunds = parseFloat(r.total_refunds || '0');
    const trueNet = parseFloat(r.total_net || '0');
    const subRev = parseFloat(r.sub_rev || '0');
    const oneTimeRev = parseFloat(r.one_time_rev || '0');
    const espGross = parseFloat(r.esp_gross || '0');
    const espTrueNet = parseFloat(r.esp_true_net || '0');

    const discrepancy = espGross - espTrueNet;
    const discrepancyPct = espGross > 0 ? (discrepancy / espGross) * 100 : 0;
    const netMargin = trueNet > 0 ? (espTrueNet / trueNet) * 100 : 0;

    return {
      clientId,
      periodStart,
      periodEnd,
      totalGrossSales: Math.round(totalGross * 100) / 100,
      totalRefunds: Math.round(totalRefunds * 100) / 100,
      totalDiscounts: Math.round((totalGross - trueNet - totalRefunds) * 100) / 100,
      trueNetRevenue: Math.round(trueNet * 100) / 100,
      subscriptionRevenue: Math.round(subRev * 100) / 100,
      organicOneTimeRevenue: Math.round(oneTimeRev * 100) / 100,
      espAttributedGrossRevenue: Math.round(espGross * 100) / 100,
      espAttributedNetRevenue: Math.round(espTrueNet * 100) / 100,
      reconciliationDiscrepancy: Math.round(discrepancy * 100) / 100,
      discrepancyPercentage: Math.round(discrepancyPct * 10) / 10,
      netContributionMargin: Math.round(netMargin * 10) / 10
    };
  }
}
